[package]
name = "energia"
version = "0.1.0"
authors = ["RÃ³bert Selvek <selverob@fit.cvut.cz>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dbus = "0.7.1"
